name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        run: |
          docker build -t $ECR_REGISTRY/bookstore-client:latest ./client
          docker build -t $ECR_REGISTRY/bookstore-server:latest ./server
          docker build -t $ECR_REGISTRY/bookstore-nginx:latest ./nginx

          docker push $ECR_REGISTRY/bookstore-client:latest
          docker push $ECR_REGISTRY/bookstore-server:latest
          docker push $ECR_REGISTRY/bookstore-nginx:latest

      - name: Run security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/bookstore-client:latest"
          format: "table"
          exit-code: 1
          severity: "CRITICAL,HIGH"
