name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          AWS_REGION: us-east-1
          ECR_REGISTRY: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t $ECR_REGISTRY/bookstore-client:latest ./client
          docker build -t $ECR_REGISTRY/bookstore-server:latest ./server
          docker build -t $ECR_REGISTRY/bookstore-nginx:latest ./nginx

          docker push $ECR_REGISTRY/bookstore-client:latest
          docker push $ECR_REGISTRY/bookstore-server:latest
          docker push $ECR_REGISTRY/bookstore-nginx:latest

      - name: Run security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/bookstore-client:latest"
          format: "table"
          exit-code: 1
          severity: "CRITICAL,HIGH"
